# Generated by Django 5.2.3 on 2025-06-19 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stuid', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('date_of_interview', models.DateField()),
                ('round1_status', models.CharField(choices=[('selected', 'Selected'), ('not_selected', 'Not Selected'), ('hold', 'Hold')], default='hold', max_length=20)),
                ('round2_status', models.CharField(blank=True, choices=[('selected', 'Selected'), ('not_selected', 'Not Selected')], max_length=20, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
